var_1: &docker_image circleci/node:8-browsers
var_2: &cache_key design-angular-kit-{{ .Branch }}-{{ checksum "package.json" }}

# Each job will inherit these defaults
anchor_1: &job_defaults
  working_directory: ~/design-angular-kit
  docker:
    - image: *docker_image

version: 2

jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm install
      - save_cache:
          key: *cache_key
          paths:
            - "node_modules"
  test:
    <<: *job_defaults
    steps:
      - checkout
      - run: export PATH=$PATH:~/design-angular-kit/node_modules/.bin/
      - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
      # - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
  lint:
    <<: *job_defaults
    steps:
      - checkout
      - run: export PATH=$PATH:~/design-angular-kit/node_modules/.bin/
      - run: npm run lint

  package:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Skip this job for Pull Requests and Fork builds
          # Note, `|| true` on the end makes this step always exit 0
          command: '[[ -v CIRCLE_PR_NUMBER
              || "$CIRCLE_PROJECT_USERNAME" != "apuliasoft"
              || "$CIRCLE_PROJECT_REPONAME" != "design-angular-kit"
          ]] && circleci step halt || true'
      # Generate and publish NPM package + Publish docs to Github Pages
  
  documentation:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Skip this job for Pull Requests and Fork builds
          # Note, `|| true` on the end makes this step always exit 0
          command: '[[ -v CIRCLE_PR_NUMBER
              || "$CIRCLE_PROJECT_USERNAME" != "apuliasoft"
              || "$CIRCLE_PROJECT_REPONAME" != "design-angular-kit"
          ]] && circleci step halt || true'

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build